name: arl-cmci
channels: [conda-forge]
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - ipykernel
  - sounddevice
  - pandas
  - seaborn
  - pip
  - pip:
      - imageio
